### ISSUE TITLE
Add a finite state machine

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdksync#107]
## Use Case
Usage of a state machine allows us to model the workflow better and show how events flow for a particular action.  Additionally, this would keep unwanted events from occurring and future additions to be easily added. 

## Describe the Solution You Would Like
I would like to see some clear definitions of defined states that pdksync can be in.  Currently, it looks like 

* setting_up_pdk
* cloning modules
* running_pdk_update
* running_pdk_convert
* validating_module
* creating_branch
* creating_commit
* pushing_branch
* creating_pr
* notifying_group
* cleaning_up

Each of these states would call actions like `create_commit` or `create_pr`.  A failure in a states forces a secondary run to know try and recreate things.

The state machine would also provide an easy way to log output during a transition from one state to the next.  Essentially this is already be done in the form of puts statement and sequential line. 

Below are two libraries I like to use:
https://github.com/aasm/aasm  (pulls in ruby-concurrent)
https://github.com/geekq/workflow (no external libs)

Overall, this would greatly cleanup the pdksync.rb file which currently contains a method called "main" with 140 lines of code.

**Comment by jordanbreen28** [comment]
Hey @logicminds, this tool is getting some love, so cleaning through historic issues.
I'm going to go ahead and close this ageing issue, please re-open if this is still relevant.
