### ISSUE TITLE
allow hooks to be called

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdksync#109]
## Use Case
I need to generate a .fixtures file from the Puppetfile found in the module (among other tasks).  I would like a script to be called post pdk update or convert via a hook method that calls a script I define in the configuration.

Example workflow:
1. rake pdksync
2. pdk update
3. pdksync calls hooks
4. hook calls script like `generate_fixtures.rb`
5. files are committed and submited in PR. 

## Describe the Solution You Would Like
A post pdk update completion hook that is called before a commit is made

## Describe Alternatives You've Considered
Have to create manually

**Comment by jordanbreen28** [comment]
Closing this ageing issue, please re-open if this is still relevant.
