### ISSUE TITLE
uninitialized constant PDK::VERSION (NameError) running rake task

### ISSUE THREAD

**Issue by DaveTCode** [puppetlabs/pdksync#116]
## Describe the Bug
Attempting to run any pdk command using bundle exec rake pdksync:* results in:
```
(FAILURE) Unable to run `pdk update`: /pdk/puppet-module-sync/.bundle/gems/ruby/2.4.0/gems/pdk-1.14.0/lib/pdk/cli/update.rb:28:in `block (2 levels) in <module:CLI>': uninitialized constant PDK::VERSION (NameError)
        from /pdk/puppet-module-sync/.bundle/gems/ruby/2.4.0/gems/cri-2.15.9/lib/cri/command.rb:360:in `run_this'
        from /pdk/puppet-module-sync/.bundle/gems/ruby/2.4.0/gems/cri-2.15.9/lib/cri/command.rb:296:in `run'
        from /pdk/puppet-module-sync/.bundle/gems/ruby/2.4.0/gems/cri-2.15.9/lib/cri/command.rb:314:in `run'
        from /pdk/puppet-module-sync/.bundle/gems/ruby/2.4.0/gems/pdk-1.14.0/lib/pdk/cli.rb:56:in `run'
        from /pdk/puppet-module-sync/.bundle/gems/ruby/2.4.0/gems/pdk-1.14.0/exe/pdk:6:in `<top (required)>'
        from /pdk/puppet-module-sync/.bundle/gems/ruby/2.4.0/bin/pdk:23:in `load'
        from /pdk/puppet-module-sync/.bundle/gems/ruby/2.4.0/bin/pdk:23:in `<main>'
```

## Expected Behavior
To actually run the PDK command

## Steps to Reproduce
I have been reproducing this locally as follows:
```
docker run -it --rm -v ${pwd}:/pdk ruby:2.4.1 bash
```
Inside the container setting up my ssh key and then:
```
bundle install --path .bundle/gems/
bundle exec rake pdksync
```

## Environment
 - latest gem (0.5.0) rather than github location
 - Platform - Docker on windows running ruby:2.4.0

## Additional Context
My Gemfile contains just
```
gem 'pdksync'
gem 'rake'
```

and my Rakefile contains just
```
require 'pdksync/rake_tasks'
```

Just to note I love that this exists and will be very pleased when I can get it working. Thanks!

**Comment by bond-os** [comment]
This happens with pdk 1.14, no issue on 1.13

**Comment by logicminds** [comment]
pdk 1.14 changed a fair bit around how things were loaded.  As a result if we are using pdk directly as a library we will need to also include some other pdk paths.  

The next release of pdk will fix these loading issues but for now you can either use 1.13 pdk gem or require 'pdk/version'.

**Comment by DaveTCode** [comment]
Great, that worked on pdk 1.14.1 (didn't on 1.14.0). Appreciate the help!
