### ISSUE TITLE
GITHUB_TOKEN not needed when GITLAB_TOKEN provided

### ISSUE THREAD

**Issue by cdenneen** [puppetlabs/pdksync#147]
## Describe the Bug
GITHUB_TOKEN shouldn't be necessary if using GITLAB_TOKEN

```
❯ export GITLAB__TOKEN=XXXXXXXXXXXXX
❯ bundle exec rake git:clone_managed_modules
rake aborted!
ArgumentError: Git platform access token for Github not set - use 'export GITHUB_TOKEN="<your token>"' to set
```

**Comment by cdenneen** [comment]
So the docs show `~/.pdksync.yml` having this didn't help. Once I moved to `$(pwd)/pdksync.yml` it worked using the `git_platform`. Not sure why the `~/.pdksync.yml` which is meant to override doesn't appear to be working.

**Comment by sanfrancrisko** [comment]
Hi @cdenneen - I'm unable to reproduce this issue. Can I ask what OS you're running on?

**Comment by cdenneen** [comment]
@sanfrancrisko OSX

**Comment by sanfrancrisko** [comment]
Same as myself...odd 🤔

**Comment by cdenneen** [comment]
@sanfrancrisko I can't seem to reproduce it now so closing this issue.
