### ISSUE TITLE
gem install doesnt seem to pickup the newly released 0.6.0 version

### ISSUE THREAD

**Issue by attachmentgenie** [puppetlabs/pdksync#157]
## Describe the Bug
while following the pdksync setup using the README in the repository, there are 2 problems

> attachmentgenie-pdksync ❯ bundle install --path .bundle/gems/                                                                                     main
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path '.bundle/gems/'`, and stop using this flag
Fetching https://github.com/puppetlabs/pdksync
fatal: Needed a single revision
Git error: command `git rev-parse --verify pdksync-externalisation-fixes` in directory

for which i raised a PR (#156), the second problem, is that after fixing the gem file, bundler install the 0.5.0 version instead of the latest released version.

> attachmentgenie-pdksync ❯ bundle install --path .bundle/gems/ 
....
Using pdk 2.2.0
Using pdksync 0.5.0 from https://github.com/puppetlabs/pdksync (at master@3b17e32)
Bundler attempted to update pdksync but its version stayed the same
Bundle updated!

## Expected Behavior
have the latest released version installed (v0.6.0) 

## Steps to Reproduce
1. follow the [How It Works Tutorial](https://github.com/puppetlabs/pdksync#how-it-works)

## Environment
 - Version ruby 2.7.0
 - Platform ubuntu 20.04

**Comment by sanfrancrisko** [comment]
Thanks for the fix to the README @attachmentgenie - I merged it.

Regarding the issue with version 0.5.0 still being used when run `bundle install`, were you on the `master` branch, by chance? We've now switched to `main` as our primary branch - I'll see if we can remove `master` to avoid confusion

**Comment by attachmentgenie** [comment]
@sanfrancrisko i just reran the howto in the readme as currently in de main branch, and that yielded a working 0.6.0 so i consider this closed now
